<?php

declare(strict_types=1);

namespace Database\Seeders;

use Domain\Game\Entities\Game;
use Domain\Game\Entities\GameCategory;
use Illuminate\Database\Seeder;

class GameSeeder extends Seeder
{
    public function run(): void
    {
        // ── Categories ────────────────────────────────────────────────────────
        $categories = [
            ['slug' => 'action',  'name' => 'Hành Động & Phiêu Lưu', 'description' => 'Game hành động tốc độ cao, thử thách phản xạ và kỹ năng sinh tồn', 'icon' => '🎯', 'color' => '#e11d48', 'sort_order' => 1],
            ['slug' => 'puzzle',  'name' => 'Câu Đố & Logic',         'description' => 'Game rèn luyện tư duy logic, giải đố và chiến lược',               'icon' => '🧩', 'color' => '#7c3aed', 'sort_order' => 2],
            ['slug' => 'arcade',  'name' => 'Arcade & Classic',        'description' => 'Game arcade kinh điển mọi thời đại, đơn giản mà nghiện',            'icon' => '🏓', 'color' => '#0284c7', 'sort_order' => 3],
            ['slug' => 'runner',  'name' => 'Endless Runner',          'description' => 'Chạy không ngừng, vượt chướng ngại vật và phá kỷ lục',              'icon' => '🏃', 'color' => '#d97706', 'sort_order' => 4],
            ['slug' => 'memory',  'name' => 'Ghi Nhớ & Phản Xạ',      'description' => 'Game luyện trí nhớ, phản xạ nhanh và tư duy tuần tự',              'icon' => '🧠', 'color' => '#059669', 'sort_order' => 5],
            ['slug' => 'casual',  'name' => 'Giải Trí Nhanh',          'description' => 'Mini-game vui nhộn, chơi 5 phút là thỏa mãn',                      'icon' => '🎲', 'color' => '#db2777', 'sort_order' => 6],
            ['slug' => 'dev',     'name' => 'Luyện Kỹ Năng Dev',       'description' => 'Game dành riêng cho developer — tốc độ, logic và thuật toán',      'icon' => '⌨️', 'color' => '#16a34a', 'sort_order' => 7],
        ];

        $catMap = [];
        foreach ($categories as $data) {
            $cat = GameCategory::updateOrCreate(['slug' => $data['slug']], $data);
            $catMap[$data['slug']] = $cat->id;
        }

        // ── Games ─────────────────────────────────────────────────────────────
        $games = [
            // ACTION
            ['category_id' => $catMap['action'], 'slug' => 'flappy-bird', 'name' => 'Flappy Bird', 'summary' => 'Nhấn để bay qua các ống, né chướng ngại vật. Đơn giản nhưng cực kỳ khó — thử xem bạn đạt được bao nhiêu điểm!', 'description_markdown' => "## Cách Chơi\n\nNhấn **Space**, **Click chuột** hoặc **chạm màn hình** để con chim bay lên. Thả ra để rơi xuống. Mục tiêu là bay qua khoảng trống giữa các cặp ống mà không chạm vào.\n\n## Mẹo\n- Nhấp liên tục ngắn thay vì giữ lâu\n- Canh khoảng cách ống trước khi nhấp\n- Tập trung vào nhịp thở đều đặn!", 'engine_path' => '/game-engines/flappy-bird/index.html', 'difficulty' => 'hard', 'controls_hint' => 'Space / Click / Tap — Nhấn để bay', 'is_featured' => true, 'meta_title' => 'Flappy Bird Online — Chơi Miễn Phí | TechHub Games', 'meta_description' => 'Chơi Flappy Bird online miễn phí trên trình duyệt. Điều khiển chú chim bay qua ống, thử thách phản xạ tối thượng.'],
            ['category_id' => $catMap['action'], 'slug' => 'asteroid-shooter', 'name' => 'Asteroid Shooter', 'summary' => 'Điều khiển tàu vũ trụ, bắn hạ tiểu hành tinh đang lao tới. Game bắn súng không gian kinh điển với đồ họa vector.', 'description_markdown' => "## Cách Chơi\n\nXoay tàu bằng **← →**, đẩy bằng **↑**, bắn bằng **Space**. Phá hủy tất cả tiểu hành tinh. Tiểu hành tinh lớn vỡ thành nhiều mảnh nhỏ.\n\n## Điều Khiển\n- **← →**: Xoay\n- **↑**: Đẩy tên lửa\n- **Space**: Bắn", 'engine_path' => '/game-engines/asteroid-shooter/index.html', 'difficulty' => 'hard', 'controls_hint' => '← → Xoay | ↑ Đẩy | Space: Bắn', 'is_featured' => true, 'meta_title' => 'Asteroid Shooter — Bắn Tiểu Hành Tinh Online | TechHub Games', 'meta_description' => 'Chơi Asteroid Shooter online miễn phí. Điều khiển tàu vũ trụ bắn hạ các tiểu hành tinh nguy hiểm.'],

            // PUZZLE
            ['category_id' => $catMap['puzzle'], 'slug' => '2048', 'name' => '2048', 'summary' => 'Trượt các ô số để gộp chúng lại và đạt tới ô số 2048. Game rèn tư duy thuật toán và chiến lược.', 'description_markdown' => "## Cách Chơi\n\nSử dụng phím mũi tên để di chuyển tất cả ô số. Khi hai ô cùng số chạm nhau, chúng gộp lại. Mục tiêu: tạo ra ô số **2048**!\n\n## Mẹo\n- Luôn giữ ô số lớn nhất ở một góc\n- Xây dựng chuỗi số giảm dần từ góc ra", 'engine_path' => '/game-engines/2048/index.html', 'difficulty' => 'medium', 'controls_hint' => '← → ↑ ↓ Phím Mũi Tên | Vuốt trên mobile', 'is_featured' => true, 'meta_title' => 'Game 2048 Online Miễn Phí — Chơi Ngay | TechHub Games', 'meta_description' => 'Chơi game 2048 online miễn phí ngay trên trình duyệt. Trượt các ô số để đạt tới 2048. Rèn luyện tư duy thuật toán.'],
            ['category_id' => $catMap['puzzle'], 'slug' => 'tetris', 'name' => 'Tetris', 'summary' => 'Game xếp khối huyền thoại — sắp xếp các tetromino để hoàn thành hàng ngang và ghi điểm cao nhất.', 'description_markdown' => "## Cách Chơi\n\nCác khối tetromino rơi từ trên xuống. Sắp xếp chúng để hoàn thành các hàng ngang đầy đủ.\n\n## Điều Khiển\n- **← →**: Di chuyển ngang\n- **↑**: Xoay khối\n- **↓**: Rơi nhanh\n- **Space**: Drop ngay", 'engine_path' => '/game-engines/tetris/index.html', 'difficulty' => 'medium', 'controls_hint' => '← → Di Chuyển | ↑ Xoay | ↓ Nhanh | Space: Drop', 'is_featured' => true, 'meta_title' => 'Tetris Online Miễn Phí — Xếp Khối Huyền Thoại | TechHub Games', 'meta_description' => 'Chơi Tetris online miễn phí trên trình duyệt. Xếp các khối tetromino để ghi điểm cao nhất. Game kinh điển mọi thời đại.'],
            ['category_id' => $catMap['puzzle'], 'slug' => 'color-flood', 'name' => 'Color Flood', 'summary' => 'Tô màu toàn bộ bảng bằng 1 màu duy nhất từ góc trên trái trong số lần di chuyển giới hạn. Đơn giản nhưng rất nghiện!', 'description_markdown' => "## Cách Chơi\n\nBắt đầu từ góc trên trái. Chọn màu để mở rộng vùng màu của bạn sang các ô liền kề cùng màu. Mục tiêu: tô màu toàn bộ bảng trong số lần di chuyển cho phép.", 'engine_path' => '/game-engines/color-flood/index.html', 'difficulty' => 'easy', 'controls_hint' => 'Click Chọn Màu — Chinh Phục Toàn Bộ Bảng', 'is_featured' => false, 'meta_title' => 'Color Flood — Game Tô Màu Online | TechHub Games', 'meta_description' => 'Chơi Color Flood online miễn phí. Tô màu toàn bộ bảng trong số bước tối thiểu. Game puzzle đơn giản, dễ chơi khó thắng.'],

            // ARCADE
            ['category_id' => $catMap['arcade'], 'slug' => 'snake', 'name' => 'Snake Classic', 'summary' => 'Game rắn săn mồi huyền thoại — ăn càng nhiều, rắn càng dài, game càng khó. Đừng cắn đuôi!', 'description_markdown' => "## Cách Chơi\n\nĐiều khiển con rắn để ăn các viên thức ăn màu đỏ. Mỗi lần ăn, rắn dài thêm 1 ô. Đừng đâm vào tường hoặc cắn đuôi!\n\n## Điều Khiển\n- **WASD** hoặc **Mũi tên**: Di chuyển\n- **Space**: Tạm dừng", 'engine_path' => '/game-engines/snake/index.html', 'difficulty' => 'easy', 'controls_hint' => 'WASD / ← → ↑ ↓ | Space: Pause', 'is_featured' => true, 'meta_title' => 'Snake Classic Online Miễn Phí — Rắn Săn Mồi | TechHub Games', 'meta_description' => 'Chơi game rắn săn mồi huyền thoại online miễn phí. Điều khiển rắn ăn mồi và đừng cắn đuôi. Game arcade kinh điển.'],
            ['category_id' => $catMap['arcade'], 'slug' => 'breakout', 'name' => 'Brick Breaker', 'summary' => 'Dùng mái chèo phản bóng để phá vỡ hàng gạch. Game arcade kinh điển Breakout ngay trên trình duyệt.', 'description_markdown' => "## Cách Chơi\n\nDi chuyển mái chèo bằng chuột hoặc ← → để giữ bóng trong sân. Phản bóng vào các khối gạch để phá hủy chúng. Phá hết gạch = qua màn.", 'engine_path' => '/game-engines/breakout/index.html', 'difficulty' => 'medium', 'controls_hint' => 'Chuột / ← → Di Chuyển Mái Chèo', 'is_featured' => false, 'meta_title' => 'Brick Breaker — Phá Gạch Online Miễn Phí | TechHub Games', 'meta_description' => 'Chơi Brick Breaker (Breakout) online miễn phí. Dùng mái chèo phản bóng phá vỡ hàng gạch. Game arcade kinh điển trên trình duyệt.'],
            ['category_id' => $catMap['arcade'], 'slug' => 'pong', 'name' => 'Pong vs CPU', 'summary' => 'Game bóng bàn 2 người đối kháng kinh điển nhất lịch sử. Đánh bại AI CPU bằng cách ghi 7 điểm trước!', 'description_markdown' => "## Cách Chơi\n\nBạn điều khiển mái chèo bên trái bằng chuột hoặc W/S. Phản bóng sang sân đối phương. Ai đạt **7 điểm** trước thắng!", 'engine_path' => '/game-engines/pong/index.html', 'difficulty' => 'easy', 'controls_hint' => 'Chuột / W•S — Đánh Bại AI', 'is_featured' => false, 'meta_title' => 'Pong vs CPU — Game Bóng Bàn Online | TechHub Games', 'meta_description' => 'Chơi Pong online vs CPU miễn phí. Game bóng bàn kinh điển đầu tiên trong lịch sử video game. Ai đạt 7 điểm trước thắng!'],

            // RUNNER
            ['category_id' => $catMap['runner'], 'slug' => 'dino-runner', 'name' => 'Dino Runner', 'summary' => 'Khủng long bé chạy vô tận, nhảy qua xương rồng và né dơi. Phiên bản offline game Chrome huyền thoại!', 'description_markdown' => "## Cách Chơi\n\nNhấn **Space** hoặc **↑** để nhảy. Nhấn **↓** để cúi tránh dơi bay. Khủng long tự chạy, tránh chướng ngại vật và sống sót càng lâu càng tốt.", 'engine_path' => '/game-engines/dino-runner/index.html', 'difficulty' => 'easy', 'controls_hint' => 'Space / ↑: Nhảy | ↓: Cúi', 'is_featured' => true, 'meta_title' => 'Dino Runner — Game Khủng Long Online | TechHub Games', 'meta_description' => 'Chơi Dino Runner online miễn phí. Điều khiển khủng long nhảy qua xương rồng như game offline Chrome huyền thoại.'],
            ['category_id' => $catMap['runner'], 'slug' => 'platformer-jump', 'name' => 'Platform Jumper', 'summary' => 'Nhảy qua các nền tảng nguy hiểm, thu thập xu vàng và leo lên càng cao càng tốt trước khi rơi xuống vực.', 'description_markdown' => "## Cách Chơi\n\nDùng **← →** hoặc **A/D** để di chuyển, **Space** hoặc **↑** để nhảy. Leo lên các nền tảng, tránh rơi xuống và thu thập xu vàng để ghi điểm.", 'engine_path' => '/game-engines/platformer-jump/index.html', 'difficulty' => 'hard', 'controls_hint' => '← → Di Chuyển | Space / ↑: Nhảy', 'is_featured' => false, 'meta_title' => 'Platform Jumper — Game Nhảy Nền Tảng Online | TechHub Games', 'meta_description' => 'Chơi Platform Jumper online miễn phí. Nhảy qua các nền tảng, thu thập xu vàng và leo lên càng cao càng tốt.'],

            // MEMORY
            ['category_id' => $catMap['memory'], 'slug' => 'memory-match', 'name' => 'Memory Match', 'summary' => 'Lật bài tìm cặp giống nhau — thách thức trí nhớ ngắn hạn của bạn. Tìm hết tất cả cặp càng nhanh càng tốt!', 'description_markdown' => "## Cách Chơi\n\nClick để lật các thẻ bài. Tìm 2 thẻ có cùng biểu tượng. Thẻ trùng giữ nguyên, không trùng úp lại — hãy ghi nhớ vị trí!", 'engine_path' => '/game-engines/memory-match/index.html', 'difficulty' => 'easy', 'controls_hint' => 'Click Lật Thẻ — Tìm Cặp Giống Nhau', 'is_featured' => false, 'meta_title' => 'Memory Match — Game Lật Bài Tìm Cặp Online | TechHub Games', 'meta_description' => 'Chơi Memory Match online miễn phí. Lật thẻ bài tìm cặp giống nhau. Rèn luyện trí nhớ ngắn hạn và khả năng tập trung.'],
            ['category_id' => $catMap['memory'], 'slug' => 'simon-says', 'name' => 'Simon Says', 'summary' => 'Nhớ và lặp lại chuỗi màu sắc ngày càng dài hơn. Bạn có thể nhớ được chuỗi bao nhiêu màu?', 'description_markdown' => "## Cách Chơi\n\nGame hiển thị chuỗi màu nhấp sáng theo thứ tự. Sau đó bạn phải nhấp lại đúng thứ tự đó. Mỗi vòng chuỗi dài thêm 1 màu.", 'engine_path' => '/game-engines/simon-says/index.html', 'difficulty' => 'medium', 'controls_hint' => 'Click Màu Theo Thứ Tự — Nhớ Chuỗi Càng Dài Càng Tốt', 'is_featured' => false, 'meta_title' => 'Simon Says — Game Ghi Nhớ Màu Sắc Online | TechHub Games', 'meta_description' => 'Chơi Simon Says online miễn phí. Nhớ và lặp lại chuỗi màu sắc ngày càng dài hơn. Thách thức giới hạn trí nhớ.'],

            // CASUAL
            ['category_id' => $catMap['casual'], 'slug' => 'whack-a-mole', 'name' => 'Whack-a-Mole', 'summary' => 'Đập chuột chũi nhô lên khỏi hang! Nhấp chuột nhanh nhất có thể trước khi chúng biến mất. Vui nhộn và thư giãn!', 'description_markdown' => "## Cách Chơi\n\nChuột chũi sẽ nhô lên ngẫu nhiên từ các lỗ. **Click nhanh** vào chúng để ghi điểm. Có 60 giây — ghi được càng nhiều điểm càng tốt!\n\n## Cảnh Báo\n- 🔴 Bom: Đừng click! (-5 điểm)\n- 🟡 Chuột vàng: (+3 điểm)\n- 🟤 Chuột thường: (+1 điểm)", 'engine_path' => '/game-engines/whack-a-mole/index.html', 'difficulty' => 'easy', 'controls_hint' => 'Click Chuột Chũi Thật Nhanh!', 'is_featured' => false, 'meta_title' => 'Whack-a-Mole — Đập Chuột Chũi Online | TechHub Games', 'meta_description' => 'Chơi Whack-a-Mole online miễn phí. Đập chuột chũi nhô lên khỏi hang nhanh nhất. Game giải trí vui nhộn.'],
            ['category_id' => $catMap['casual'], 'slug' => 'math-sprint', 'name' => 'Math Sprint', 'summary' => 'Trả lời phép tính nhanh nhất có thể! 60 giây, mỗi câu đúng +1 điểm. Developer giỏi phải giỏi tính toán!', 'description_markdown' => "## Cách Chơi\n\nMỗi câu là một phép tính đơn giản (+, -, ×). Nhập đáp án và nhấn **Enter**. Đúng +1 điểm, sai -1 điểm. Có 60 giây!", 'engine_path' => '/game-engines/math-sprint/index.html', 'difficulty' => 'medium', 'controls_hint' => 'Nhập Đáp Án + Enter — Trả Lời Nhanh Nhất!', 'is_featured' => false, 'meta_title' => 'Math Sprint — Toán Học Nhanh Online | TechHub Games', 'meta_description' => 'Chơi Math Sprint online miễn phí. Trả lời phép tính nhanh nhất trong 60 giây. Luyện tư duy tính toán tốc độ cao.'],

            // DEV
            ['category_id' => $catMap['dev'], 'slug' => 'dev-typing-speed', 'name' => 'Dev Typing Speed Test', 'summary' => 'Kiểm tra tốc độ gõ code của bạn với các đoạn code JavaScript, Python, SQL thực tế. WPM càng cao càng tốt!', 'description_markdown' => "## Cách Chơi\n\nBạn được hiển thị một đoạn code thực tế. Hãy gõ lại chính xác từng ký tự trong **60 giây**.\n\n## Xếp Hạng\n- 🥉 < 40 WPM: Người mới\n- 🥈 40–70 WPM: Intermediate\n- 🥇 > 70 WPM: Senior Dev!", 'engine_path' => '/game-engines/dev-typing-speed/index.html', 'difficulty' => 'hard', 'controls_hint' => 'Bàn Phím — Gõ Code Càng Nhanh Càng Tốt', 'is_featured' => true, 'meta_title' => 'Dev Typing Speed Test — Kiểm Tra Tốc Độ Gõ Code | TechHub Games', 'meta_description' => 'Test tốc độ gõ code với JavaScript, Python, SQL. Xem bạn là Junior hay Senior Developer? Chơi miễn phí trên TechHub.'],
        ];

        foreach ($games as $data) {
            Game::updateOrCreate(['slug' => $data['slug']], array_merge($data, [
                'is_active'   => true,
                'play_count'  => rand(100, 5000),
            ]));
        }
    }
}
