<?php

declare(strict_types=1);

namespace Domain\Tool\Tools\Seo;

use Domain\Tool\Contracts\ToolContract;
use Domain\Tool\Enums\ToolEngineType;
use Domain\Tool\ValueObjects\ToolResult;

class MetaTagGeneratorTool implements ToolContract
{
    public function slug(): string
    {
        return 'meta-tag-generator';
    }

    public function name(): string
    {
        return 'Tạo Thẻ Meta HTML5 Chuẩn SEO Onpage';
    }

    public function categorySlug(): string
    {
        return 'seo';
    }

    public function summary(): string
    {
        return 'Tạo mã HTML5 thẻ Meta chuẩn SEO: Title, Description, Keywords, Canonical, Robots và phân tích SEO Onpage.';
    }

    public function engineType(): ToolEngineType
    {
        return ToolEngineType::ServerSync;
    }

    public function validationRules(): array
    {
        return [
            'title' => ['required', 'string', 'max:255'],
            'description' => ['required', 'string', 'max:500'],
            'keywords' => ['nullable', 'string', 'max:500'],
            'canonical_url' => ['nullable', 'string', 'max:500'],
            'author' => ['nullable', 'string', 'max:150'],
            'language' => ['nullable', 'string', 'max:10'],
            'robots_index' => ['sometimes', 'string', 'in:index,noindex'],
            'robots_follow' => ['sometimes', 'string', 'in:follow,nofollow'],
            'robots_noarchive' => ['sometimes', 'boolean'],
            'robots_nosnippet' => ['sometimes', 'boolean'],
            'robots_noimageindex' => ['sometimes', 'boolean'],
            'charset' => ['sometimes', 'string', 'max:20'],
            'viewport' => ['sometimes', 'string', 'max:100'],
        ];
    }

    public function execute(array $input): ToolResult
    {
        $startTime = hrtime(true);

        $title = trim((string) ($input['title'] ?? ''));
        $description = trim((string) ($input['description'] ?? ''));
        $keywords = trim((string) ($input['keywords'] ?? ''));
        $canonicalUrl = trim((string) ($input['canonical_url'] ?? ''));
        $author = trim((string) ($input['author'] ?? ''));
        $language = trim((string) ($input['language'] ?? 'vi'));
        $robotsIndex = (string) ($input['robots_index'] ?? 'index');
        $robotsFollow = (string) ($input['robots_follow'] ?? 'follow');
        $robotsNoArchive = !empty($input['robots_noarchive']);
        $robotsNoSnippet = !empty($input['robots_nosnippet']);
        $robotsNoImageIndex = !empty($input['robots_noimageindex']);
        $charset = (string) ($input['charset'] ?? 'UTF-8');
        $viewport = (string) ($input['viewport'] ?? 'width=device-width, initial-scale=1.0');

        // Compile Robots Directive
        $robotsParts = [$robotsIndex, $robotsFollow];
        if ($robotsNoArchive) $robotsParts[] = 'noarchive';
        if ($robotsNoSnippet) $robotsParts[] = 'nosnippet';
        if ($robotsNoImageIndex) $robotsParts[] = 'noimageindex';
        $robotsContent = implode(', ', $robotsParts);

        // Generate HTML Tag Lines
        $lines = [];
        $lines[] = '<!-- Technical & SEO Meta Tags Generated by TechHub.vn -->';
        $lines[] = '<meta charset="' . htmlspecialchars($charset, ENT_QUOTES, 'UTF-8') . '">';
        $lines[] = '<meta name="viewport" content="' . htmlspecialchars($viewport, ENT_QUOTES, 'UTF-8') . '">';
        $lines[] = '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
        $lines[] = '';
        $lines[] = '<!-- Primary Meta Tags -->';
        $lines[] = '<title>' . htmlspecialchars($title, ENT_QUOTES, 'UTF-8') . '</title>';
        $lines[] = '<meta name="title" content="' . htmlspecialchars($title, ENT_QUOTES, 'UTF-8') . '">';
        $lines[] = '<meta name="description" content="' . htmlspecialchars($description, ENT_QUOTES, 'UTF-8') . '">';
        
        if (!empty($keywords)) {
            $lines[] = '<meta name="keywords" content="' . htmlspecialchars($keywords, ENT_QUOTES, 'UTF-8') . '">';
        }

        if (!empty($author)) {
            $lines[] = '<meta name="author" content="' . htmlspecialchars($author, ENT_QUOTES, 'UTF-8') . '">';
        }

        $lines[] = '<meta name="robots" content="' . htmlspecialchars($robotsContent, ENT_QUOTES, 'UTF-8') . '">';
        $lines[] = '<meta name="googlebot" content="' . htmlspecialchars($robotsContent, ENT_QUOTES, 'UTF-8') . '">';
        
        if (!empty($language)) {
            $lines[] = '<meta name="language" content="' . htmlspecialchars($language, ENT_QUOTES, 'UTF-8') . '">';
        }

        if (!empty($canonicalUrl)) {
            $lines[] = '';
            $lines[] = '<!-- Canonical URL -->';
            $lines[] = '<link rel="canonical" href="' . htmlspecialchars($canonicalUrl, ENT_QUOTES, 'UTF-8') . '">';
        }

        $metaHtml = implode("\n", $lines);

        // SEO Audit Checks
        $audit = [
            'has_title' => !empty($title),
            'title_length' => mb_strlen($title),
            'title_length_status' => (mb_strlen($title) >= 30 && mb_strlen($title) <= 60) ? 'good' : 'warning',
            'has_description' => !empty($description),
            'description_length' => mb_strlen($description),
            'description_length_status' => (mb_strlen($description) >= 70 && mb_strlen($description) <= 160) ? 'good' : 'warning',
            'has_canonical' => !empty($canonicalUrl),
            'is_indexable' => 'index' === $robotsIndex,
            'is_followable' => 'follow' === $robotsFollow,
            'has_charset' => true,
            'has_viewport' => true,
        ];

        $executionTimeMs = (int) round((hrtime(true) - $startTime) / 1e+6);

        return ToolResult::success([
            'result' => $metaHtml,
            'meta_html' => $metaHtml,
            'tag_count' => count(array_filter($lines, fn ($l) => str_starts_with($l, '<'))),
            'audit' => $audit,
            'summary_data' => [
                'title' => $title,
                'description' => $description,
                'canonical' => $canonicalUrl ?: 'Chưa cấu hình (Khuyên dùng)',
                'robots' => $robotsContent,
            ],
        ], executionTimeMs: $executionTimeMs);
    }
}
