<?php

declare(strict_types=1);

namespace Domain\Tool\Tools\Seo;

use Domain\Tool\Contracts\ToolContract;
use Domain\Tool\Enums\ToolEngineType;
use Domain\Tool\ValueObjects\ToolResult;

class RobotsTxtGeneratorTool implements ToolContract
{
    public function slug(): string
    {
        return 'robots-txt-generator';
    }

    public function name(): string
    {
        return 'Tạo & Kiểm Tra Tệp Robots.txt';
    }

    public function categorySlug(): string
    {
        return 'seo';
    }

    public function summary(): string
    {
        return 'Tạo và kiểm tra cú pháp tệp robots.txt chuẩn SEO, hỗ trợ chặn AI Bot, thiết lập Crawl-delay và Sitemap.';
    }

    public function engineType(): ToolEngineType
    {
        return ToolEngineType::ServerSync;
    }

    public function validationRules(): array
    {
        return [
            'preset' => ['sometimes', 'string', 'in:default,allow_all,block_all,wordpress,laravel,block_ai_bots,custom'],
            'default_user_agent' => ['sometimes', 'string', 'max:50'],
            'disallow_paths' => ['nullable', 'string', 'max:2000'],
            'allow_paths' => ['nullable', 'string', 'max:2000'],
            'crawl_delay' => ['nullable', 'integer', 'min:0', 'max:60'],
            'sitemap_url' => ['nullable', 'string', 'max:500'],
            'block_ai_crawlers' => ['sometimes', 'boolean'],
            'raw_robots_txt' => ['nullable', 'string', 'max:5000'],
        ];
    }

    public function execute(array $input): ToolResult
    {
        $startTime = hrtime(true);

        $preset = (string) ($input['preset'] ?? 'default');
        $sitemapUrl = trim((string) ($input['sitemap_url'] ?? 'https://example.com/sitemap.xml'));
        $crawlDelay = isset($input['crawl_delay']) && '' !== $input['crawl_delay'] ? (int) $input['crawl_delay'] : null;
        $blockAi = !empty($input['block_ai_crawlers']);

        $lines = [];
        $lines[] = '# Robots.txt generated by TechHub.vn (SEO Tools)';
        $lines[] = '# Crawlers policy configuration for Search Engines & AI Bots';
        $lines[] = '';

        if ('block_all' === $preset) {
            $lines[] = 'User-agent: *';
            $lines[] = 'Disallow: /';
        } elseif ('allow_all' === $preset) {
            $lines[] = 'User-agent: *';
            $lines[] = 'Disallow:';
            $lines[] = 'Allow: /';
        } elseif ('wordpress' === $preset) {
            $lines[] = 'User-agent: *';
            $lines[] = 'Disallow: /wp-admin/';
            $lines[] = 'Allow: /wp-admin/admin-ajax.php';
            $lines[] = 'Disallow: /wp-includes/';
            $lines[] = 'Allow: /wp-includes/js/';
            $lines[] = 'Allow: /wp-includes/images/';
            $lines[] = 'Disallow: /trackback/';
            $lines[] = 'Disallow: /xmlrpc.php';
        } elseif ('laravel' === $preset) {
            $lines[] = 'User-agent: *';
            $lines[] = 'Disallow: /admin/';
            $lines[] = 'Disallow: /api/';
            $lines[] = 'Disallow: /telescope/';
            $lines[] = 'Disallow: /horizon/';
            $lines[] = 'Allow: /';
        } else {
            // Default / Custom Generator
            $lines[] = 'User-agent: *';
            
            $disallowInput = (string) ($input['disallow_paths'] ?? "/admin/\n/login\n/api/private/");
            $disallowLines = array_filter(array_map('trim', explode("\n", $disallowInput)));
            if (empty($disallowLines)) {
                $lines[] = 'Disallow:';
            } else {
                foreach ($disallowLines as $d) {
                    $lines[] = 'Disallow: ' . $d;
                }
            }

            $allowInput = (string) ($input['allow_paths'] ?? "/public/\n/css/\n/js/\n/images/");
            $allowLines = array_filter(array_map('trim', explode("\n", $allowInput)));
            foreach ($allowLines as $a) {
                $lines[] = 'Allow: ' . $a;
            }
        }

        if ($crawlDelay !== null && $crawlDelay > 0) {
            $lines[] = 'Crawl-delay: ' . $crawlDelay;
        }

        // Block Popular AI Web Scrapers / LLM Bots
        if ($blockAi || 'block_ai_bots' === $preset) {
            $lines[] = '';
            $lines[] = '# Block AI Bots & Scrapers (OpenAI, Anthropic, Common Crawl, Perplexity)';
            $aiBots = ['GPTBot', 'ChatGPT-User', 'CCBot', 'anthropic-ai', 'Claude-Web', 'PerplexityBot', 'Bytespider'];
            foreach ($aiBots as $bot) {
                $lines[] = 'User-agent: ' . $bot;
                $lines[] = 'Disallow: /';
                $lines[] = '';
            }
            // Remove trailing empty line
            array_pop($lines);
        }

        // Add Sitemap Directive
        if (!empty($sitemapUrl)) {
            $lines[] = '';
            $lines[] = 'Sitemap: ' . $sitemapUrl;
        }

        $robotsTxtContent = implode("\n", $lines);

        $isEn = (class_exists(\Illuminate\Support\Facades\Facade::class) && \Illuminate\Support\Facades\Facade::getFacadeApplication())
            ? \Illuminate\Support\Facades\App::getLocale() === 'en'
            : false;

        // Validation Analysis
        $warnings = [];
        if (str_contains($robotsTxtContent, 'Disallow: /') && !str_contains($robotsTxtContent, 'User-agent: GPTBot') && ('block_all' === $preset)) {
            $warnings[] = $isEn ? 'WARNING: You are blocking the entire website from all search engines (Disallow: /).' : 'CẢNH BÁO: Bạn đang chặn toàn bộ website khỏi mọi công cụ tìm kiếm (Disallow: /).';
        }
        if (empty($sitemapUrl)) {
            $warnings[] = $isEn ? 'Recommendation: You should declare your XML Sitemap URL at the end of the file for faster indexing.' : 'Khuyến nghị: Nên khai báo đường dẫn Sitemap XML ở cuối tệp để Bot index nhanh hơn.';
        }

        $executionTimeMs = (int) round((hrtime(true) - $startTime) / 1e+6);

        return ToolResult::success([
            'result' => $robotsTxtContent,
            'robots_txt' => $robotsTxtContent,
            'line_count' => count($lines),
            'has_sitemap' => !empty($sitemapUrl),
            'ai_bots_blocked' => $blockAi || 'block_ai_bots' === $preset,
            'warnings' => $warnings,
        ], executionTimeMs: $executionTimeMs);
    }
}
